### ISSUE TITLE
Move the backend webcompat.com triage dashboard code to here

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#104]
This will 
* simplify the code on webcompat.com
* remove the CORS issues identified in https://github.com/webcompat/webcompat.com/issues/2866

It is the server side of https://github.com/webcompat/webcompat-metrics-client/issues/172

**Comment by magsout** [comment]
coool thanks Karl

**Comment by karlcow** [comment]
@magsout 
What `/data/triage-bugs` should return to be compatible with your current requests?

**Comment by karlcow** [comment]
Ah I guess the same thing which is returned by 
https://webcompat.com/api/issues/category/needstriage?per_page=100

**Comment by karlcow** [comment]
The URL to github is 
```
https://api.github.com/repos/webcompat/webcompat-tests/issues?sort=created&per_page=100&direction=asc&milestone=1
```

**Comment by karlcow** [comment]
@magsout this is moved. 
https://webcompat-metrics-pr-105.herokuapp.com/ (PR deploy)

**Comment by karlcow** [comment]
Once this is fully merged and deployed I'll remove the code on webcompat.com
https://github.com/webcompat/webcompat.com/issues/2881
