### ISSUE TITLE
Work out how to send gzipped data for the json

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#24]

**Comment by karlcow** [comment]
> However on some environments it is not possible to deploy with such 'middleman'. One of example of that environment is Heroku: even their documentation says your app should be connected directly to clients via Gunicorn. Therefore, gzipping has to be implemented on your app's end.
— http://flask.pocoo.org/snippets/122/

yet another minus point for Heroku
ping @miketaylr

**Comment by karlcow** [comment]
So to solve this basically we need to install a module or write it myself. Not complicated code, but still.
Here an example https://github.com/libwilliam/flask-compress/blob/master/flask_compress.py

**Comment by karlcow** [comment]
@magsout I propose we push this one for the next iteration.

**Comment by magsout** [comment]
@karlcow sounds good

**Comment by laghee** [comment]
@karlcow @magsout Is this still a relevant issue in terms of perf improvement, or should it be closed because we've moved in a different direction?

**Comment by karlcow** [comment]
It's kind of orthogonal to the DB, but indeed the DB removes the huge file we were requesting most of the time, and then improve quite a lot the performances.

I think we can safely close it. And we could reopen if we feel it is necessary to improve the perf in the future.
https://devcenter.heroku.com/articles/compressing-http-messages-with-gzip
