### ISSUE TITLE
Adds CORS headers 

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#26]
Allow https://webcompat.github.io/webcompat-metrics-client/ to fetch http://webcompat-metrics.herokuapp.com/data/needsdiagnosis-timeline so @magsout client is working.

**Comment by magsout** [comment]
Thanks <3 ;)

**Comment by miketaylr** [comment]
Over at https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-19&to=2018-06-19 I see:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-timeline?from=2018-05-19&to=2018-06-19. (Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’).

Unsure if expected or not.

**Comment by karlcow** [comment]
Yup seen that. Usually it's because of cookies no? or is it mandatory because of HTTPS?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

> Credentials are cookies, authorization headers or TLS client certificates.

bingo TLS

Let's open a new issue.

**Comment by karlcow** [comment]
Opened #29 Thanks @miketaylr
