### ISSUE TITLE
Adds CORS headers  for developement

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat-metrics-server#31]
@karlcow it ok on production but on developement not.

![capture d ecran 2018-06-21 a 21 40 47](https://user-images.githubusercontent.com/1997108/41741573-c8340652-759b-11e8-9b32-52b411cdcdc5.png)

**Comment by karlcow** [comment]
@magsout This should be working now

**Comment by magsout** [comment]
@karlcow still same message and error
![capture d ecran 2018-06-21 a 22 07 55](https://user-images.githubusercontent.com/1997108/41742867-9828e078-759f-11e8-8c68-6eaf7e303d9e.png)
![capture d ecran 2018-06-21 a 22 08 04](https://user-images.githubusercontent.com/1997108/41742868-98497d6a-759f-11e8-972b-247a1d87ab47.png)

**Comment by karlcow** [comment]
hmm weird


```
→ http HEAD https://webcompat-metrics-staging.herokuapp.com/data/needsdiagnosis-timeline
```

Or is it when you test locally? aka not hosted.

```http
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://webcompat.github.io
Connection: keep-alive
Content-Length: 108434
Content-Type: application/json
Date: Thu, 21 Jun 2018 20:10:30 GMT
Server: gunicorn/19.8.1
Vary: Origin
Via: 1.1 vegur
```

`Access-Control-Allow-Origin: https://webcompat.github.io` this tells to accept only from webcompat.github.io.

**Comment by magsout** [comment]
http://localhost:3001/?from=2018-05-21&to=2018-06-21

**Comment by karlcow** [comment]
so indeed there are two ways to solve this:

* to change to allow all domains with `*`
* to use a proxy server which changes the value on the fly.

Let me add `*`

**Comment by karlcow** [comment]
Pull request in the pipe #32
