### ISSUE TITLE
Add env/ to .gitignore

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-server#33]
Unless this directory might be used for something else, ignoring it will allow for an alternate local virtual environment configuration (like, oops, mine -- which I set up with virtualenv for this project) (not to be confused with pipenv, which I used for another project ... oh, python 🐍 )

**Edit:** Also added `.vscode` so my IDE settings file is excluded.

**Comment by miketaylr** [comment]
Possibly this can be closed, depending on https://github.com/webcompat/webcompat-metrics-server/pull/34#issuecomment-410553639?

**Comment by laghee** [comment]
Oops! Yep!
