### ISSUE TITLE
Set up to receive github webhooks

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-server#43]
It looks like a lot of the infrastructure for this was already set up in webcompat.com but isn't currently used (unless I'm misunderstanding something). I'll try to port over as much of that as I can, and then see what needs to be added/tweaked from there.

**Comment by laghee** [comment]
OK, so this turned out to crazy big and made @karlcow want to go back on vacation, so I'm splitting it into six issues so that scary monster of a PR #44 can be made more manageable:

- #46 (just the webhook handler blueprint - `webhooks/__init__.py`)
- #47 (the webhook handler `helpers.py` module)
- #48 (changes to `ochazuke` to attach webhook blueprint and add logging config)
- #49 (`test_webhooks.py`)
- #50 (CircleCI config minor changes for database)
- #51 (additions and edit to `models.py`)

**Comment by karlcow** [comment]
Thanks ❤️

**Comment by laghee** [comment]
Closing this as covered by issues listed above.
