### ISSUE TITLE
Decide what to do on failures to update database tables

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-server#45]
@karlcow from PR #44 :
> And I also wonder what we would want to do if update_db fails. Do we want to log this? Do we want
> to queue it again for another time later?

me from same:

> I was wondering this, too. GitHub keeps a log of recent webhook payloads, so they can be re-triggered manually (not sure how long or how many it keeps at a time.) That's probably not a solution, but it's a good thing to know in case of some future disastrous failure. I would think we'd definitely want to log failures, and maybe set a certain number of re-tries before saving the data in a temp file or something? Not sure what all the options would be.

**Comment by karlcow** [comment]
Yes. :) logging is good. But not sure if at a point we might need to run a kind of integrity feature ourselves, because GitHub events are also not 100% reliable.

**Comment by laghee** [comment]
Definitely. I've been getting very interested in automation and devops stuff, so this would be a good place to get some practice in. 😄

**Comment by laghee** [comment]
This has changed shape somewhat since the original DB idea. Since we are now relying on cron jobs rather than GitHub webhooks, what best practices should we implement to ensure database integrity and guard against data loss?

We're currently logging errors to `stdout` on Heroku, which stores 1500 lines of logs for a maximum of 7 days before they get wiped. The [12 Step App](https://12factor.net/logs) says that's the way to go and that "the environment" should handle routing to an archive.

Since we're not set up with containers or anything that fancy yet, we may need to start with some sort of routing script that we engineer. Or we could explore some of the Heroku log add-ons. At minimum, it would be good to receive alerts on write failures. Being able to search more than 1500 lines/7 days would also be a plus.

Two decent-looking add-on options with free tiers:

[Papertrail](https://elements.heroku.com/addons/papertrail) - 10MB daily, 2 days of search, 7-days archive, saved searches, filtering, alerts included

[Timber.io](https://elements.heroku.com/addons/timber-logging) - 1GB monthly, 24 hours of search, "log parsing" (no details yet, so not sure what that entails or what you can do with parsed data), filtering, real-time alerts included

Thoughts @karlcow 🐄 ?

**Comment by karlcow** [comment]
Yup looked at the two proposals. 
Probably Papertrail is worth the try, and if we are not satisfied we can imagine something else. We don't rely that much on logs for now.

so 👍

**Comment by laghee** [comment]
Cool. I've now provisioned Papertrail, which is set up to send me email alerts on platform errors or Scheduler errors (failures to add counts to the DB). (@karlcow I assumed you weren't dying for any more email alerts on your plate, but if you want me to set it up to ping you, too, just let me know. ✉️ ✉️ ✉️ )

More info below to remind me for dev docs:

Their dashboard is pretty straightforward and you can go straight to it by setting up a bookmark for https://addons-sso.heroku.com/apps/webcompat-metrics/addons/papertrail (keeps you from having to click through all of heroku's dash to get there). Alternatively, you can open a browser window from the cli with `heroku addons:open --app webcompat-metrics papertrail`.

There's also a cli that can be installed locally with `heroku plugins:install heroku-papertrail` in case you hate fancy GUIs and prefer to live on the command line. You can search and tail logs directly with the plugin: `heroku pt [OPTIONAL SEARCH QUERY] -a webcompat-metrics [--tail]`.
