### ISSUE TITLE
Domain name for webcompat metrics server

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#6]
Discussing with @miketaylr about it.
We decided to use whatever heroku will give us at first.
And if we want later to ask mozilla to redirect arewecompatibleyet.com to this instance.

**Comment by miketaylr** [comment]
@karlcow is https://webcompat.github.io the plan for now, or do we want to move away from that at some point?

**Comment by karlcow** [comment]
not sure, we seem to be ok with https://webcompat.github.io/webcompat-metrics-client/?from=2018-09-20&to=2018-10-13 

It creates a dependency on GitHub.io for the domain name, which is never ideal. At least we could ask arewecompatibleyet.com to shadow webcompat.github.io/webcompat-metrics-client

**Comment by karlcow** [comment]
Let's close this for now.
