### ISSUE TITLE
Update tests for weekly reports endpoint

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-server#75]

**Comment by karlcow** [comment]
@laghee do you need help here? What is it about?

**Comment by laghee** [comment]
@karlcow This is me needing to change this section of `test_ochazuke`: https://github.com/webcompat/webcompat-metrics-server/blob/d3e4745e2e99686060f3466aed5238aa34e33ecb/tests/unit/test_ochazuke.py#L28
because I changed the format of the weekly count json response to match the style of the needsdiagnosis one. I need to update the dummy data and the tests to conform to the count/timestamp setup.

It's probably better that I address #78 first (just in case I need to tweak the format again).

**Comment by karlcow** [comment]
house cleaning. 👻 

#78 was done.
is there a blocker for this one?

**Comment by laghee** [comment]
Nope! I'll put this on my running list.

**Comment by laghee** [comment]
No, my bad -- there is a blocker. And that blocker is... while this code still exist, nothing uses it anymore. 😜

First the testing files were revamped in PR #108, then I actually fixed this in PR #122. I discovered some weirdness in the tests while trying to figure this out, though, so will open a new issue to clean that up.
