### ISSUE TITLE
Fix weekly counts for 2019

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-server#78]
This is why hard-coding is bad... 😉

I need to fix my script in pythonanywhere to extend its data collection beyond 2018.

**Comment by laghee** [comment]
There's no PR for this, but it's now fixed (with the code equivalent of paper clips and duct tape, but fixed). 
![screenshot 2019-01-27 18 55 55](https://user-images.githubusercontent.com/20972610/51804772-36539780-2265-11e9-9d3c-bffdf87f8876.png)

**Comment by karlcow** [comment]
Thanks!

**Comment by magsout** [comment]
👍
