### ISSUE TITLE
Script for weekly new issues to tie to the scheduler

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-server#80]
In the same spirit of #64 
we need a version of @laghee script in `bin/` so we can collect the data for the weekly number of new issues.

(note that we could collect the absolute number per day and compute on the server side how many issues that creates.)

**Comment by laghee** [comment]
I'm working on a daily script -- that way the current week's running count could still be displayed (i.e., no waiting until the week is officially over in UTC).

Also Heroku's scheduler doesn't appear to have any option less frequent than daily (so for an automated weekly count, some part of the script would have to run daily anyway -- with some sort of abandon-task boolean test tied to the day of the week).

**Comment by laghee** [comment]
Got a script working locally. Will send in a PR in the next couple of days.
